export const DESTINATIONS = [
  {
    id: 'maasai-mara',
    slug: 'maasai-mara',
    name: 'Maasai Mara',
    region: 'Rift Valley & Central',
    description: 'The crown jewel of African wilderness, famous for the Great Migration.',
    overview: 'The Maasai Mara National Reserve is one of the most popular tourism destinations in Kenya. The reserve is located in the Great Rift Valley in primarily open grassland.',
    highlights: ['Great Migration (July-Oct)', 'Hot Air Balloon Safaris', 'Maasai Cultural Encounters'],
    wildlife: ['Lions', 'Leopards', 'Cheetahs', 'Elephants', 'Buffaloes', 'Rhinos'],
    activities: ['Game Drives', 'Walking Safaris', 'Cultural Visits'],
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 30, y: 70 },
  },
  {
    id: 'amboseli',
    slug: 'amboseli',
    name: 'Amboseli',
    region: 'Southern Kenya',
    description: 'Iconic views of Mount Kilimanjaro and large herds of elephants.',
    overview: 'Amboseli National Park is known for its large elephant herds and views of immense Mount Kilimanjaro, across the border in Tanzania.',
    highlights: ['Views of Mt. Kilimanjaro', 'Large Elephant Herds', 'Observation Hill'],
    wildlife: ['Elephants', 'Lions', 'Cheetahs', 'Giraffes', 'Zebras'],
    activities: ['Game Viewing', 'Photography', 'Bird Watching'],
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 60, y: 80 },
  },
  {
    id: 'tsavo',
    slug: 'tsavo',
    name: 'Tsavo East & West',
    region: 'Southern Kenya',
    description: 'One of the oldest and largest parks in Kenya, known for its red elephants.',
    overview: 'Tsavo is divided into East and West. Tsavo East is famous for its "red elephants" and the Yatta Plateau, while Tsavo West is known for Mzima Springs and Shetani Lava Flow.',
    highlights: ['Mzima Springs', 'Red Elephants', 'Lugard Falls'],
    wildlife: ['Elephants', 'Rhinos', 'Lions', 'Leopards', 'Hippos'],
    activities: ['Game Drives', 'Hiking', 'Cave Exploration'],
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 75, y: 75 },
  },
  {
    id: 'mount-kenya',
    slug: 'mount-kenya',
    name: 'Mount Kenya',
    region: 'Rift Valley & Central',
    description: 'Africa\'s second highest peak, offering breathtaking alpine scenery.',
    overview: 'Mount Kenya is the highest mountain in Kenya and the second-highest in Africa. It is a UNESCO World Heritage Site and offers diverse ecosystems.',
    highlights: ['Alpine Scenery', 'Peak Climbing', 'Unique Flora'],
    wildlife: ['Elephants', 'Tree Hyrax', 'White-tailed Mongoose', 'Sunbirds'],
    activities: ['Mountain Climbing', 'Hiking', 'Camping'],
    image: 'https://images.unsplash.com/photo-1627662236973-4fda8358cb2a?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 65, y: 45 },
  },
  {
    id: 'diani-beach',
    slug: 'diani',
    name: 'Diani Beach',
    region: 'Coastal & Marine',
    description: 'Pristine white sands and turquoise waters of the Indian Ocean.',
    overview: 'Diani Beach is a major beach on the Indian Ocean coast of Kenya. It is located 30 kilometres south of Mombasa.',
    highlights: ['White Sand Beaches', 'Coral Reefs', 'Water Sports'],
    wildlife: ['Dolphins', 'Sea Turtles', 'Colobus Monkeys'],
    activities: ['Snorkeling', 'Diving', 'Kite Surfing', 'Deep Sea Fishing'],
    image: 'https://images.unsplash.com/photo-1589979481223-bed89d344549?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 85, y: 90 },
  },
  {
    id: 'samburu',
    slug: 'samburu',
    name: 'Samburu',
    region: 'Northern Kenya',
    description: 'Rugged landscapes and unique wildlife species found only in the north.',
    overview: 'Samburu National Reserve is a rugged and semi-desert park located in the Samburu District in the Rift Valley Province of Kenya.',
    highlights: ['Ewaso Ng\'iro River', 'Samburu Special Five', 'Rugged Terrain'],
    wildlife: ['Gerenuk', 'Grevy\'s Zebra', 'Reticulated Giraffe', 'Beisa Oryx', 'Somali Ostrich'],
    activities: ['Game Viewing', 'Cultural Visits', 'Camel Safaris'],
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 65, y: 35 },
  },
  {
    id: 'lake-nakuru',
    slug: 'lake-nakuru',
    name: 'Lake Nakuru',
    region: 'Rift Valley & Central',
    description: 'Famous for its pink flamingos and as a sanctuary for rhinos.',
    overview: 'Lake Nakuru National Park is best known for its thousands, sometimes millions of flamingos nesting along the shores.',
    highlights: ['Flamingos', 'Rhino Sanctuary', 'Baboon Cliff'],
    wildlife: ['Rhinos', 'Flamingos', 'Pelicans', 'Waterbucks', 'Rothschild Giraffes'],
    activities: ['Bird Watching', 'Game Drives', 'Picnicking'],
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 55, y: 55 },
  },
  {
    id: 'nairobi-np',
    slug: 'nairobi-np',
    name: 'Nairobi National Park',
    region: 'Nairobi Area',
    description: 'The world\'s only wildlife park within a capital city.',
    overview: 'Nairobi National Park is a national park in Kenya that was established in 1946. It is located approximately 7 kilometres south of the centre of Nairobi.',
    highlights: ['City Skyline Views', 'Ivory Burning Site', 'Rhino Breeding'],
    wildlife: ['Rhinos', 'Lions', 'Leopards', 'Hyenas', 'Buffaloes', 'Giraffes'],
    activities: ['Game Drives', 'Walking Trails', 'Nairobi Safari Walk'],
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
    coordinates: { x: 62, y: 65 },
  },
];

export const SAFARIS = [
  {
    id: 'mara-safari',
    name: 'Maasai Mara Signature',
    slug: 'maasai-mara',
    duration: '3 Days / 2 Nights',
    basePrice: 450,
    category: 'Safari',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    highlights: ['Great Migration crossing', 'Big Five spotting', 'Hot air balloon option'],
    itinerary: [
      { day: 1, title: 'Arrival & Evening Game Drive', description: 'Arrive at the Mara and settle into your lodge before an evening drive.' },
      { day: 2, title: 'Full Day Game Exploration', description: 'Spend the entire day tracking the migration and the Big Five.' },
      { day: 3, title: 'Morning Drive & Departure', description: 'One last sunrise game drive before heading back to Nairobi.' },
    ],
    included: ['Park fees', 'Professional guide', 'Meals', 'Water'],
  },
  {
    id: 'amboseli-safari',
    name: 'Amboseli Elephant Trail',
    slug: 'amboseli',
    duration: '2 Days / 1 Night',
    basePrice: 320,
    category: 'Safari',
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
    highlights: ['Kilimanjaro views', 'Elephant herds', 'Bird watching'],
    itinerary: [
      { day: 1, title: 'Nairobi to Amboseli', description: 'Scenic drive to Amboseli with an afternoon game drive.' },
      { day: 2, title: 'Sunrise Drive & Return', description: 'Morning game drive with views of the mountain peak.' },
    ],
    included: ['Park fees', 'Professional guide', 'Meals'],
  },
  {
    id: 'tsavo-safari',
    name: 'Tsavo Red Elephant Quest',
    slug: 'tsavo',
    duration: '3 Days / 2 Nights',
    basePrice: 380,
    category: 'Safari',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    highlights: ['Mzima Springs', 'Red elephants', 'Shetani lava flow'],
    itinerary: [
      { day: 1, title: 'Tsavo West Exploration', description: 'Visit Mzima Springs and the lava flows.' },
      { day: 2, title: 'Tsavo East Crossing', description: 'Drive across to the vast plains of Tsavo East.' },
      { day: 3, title: 'Final Game Drive', description: 'Morning game drive and departure.' },
    ],
    included: ['Park fees', 'Professional guide', 'Meals'],
  },
  {
    id: 'nairobi-tour',
    name: 'Nairobi City & Wildlife',
    slug: 'nairobi',
    duration: 'Full Day',
    basePrice: 120,
    category: 'City Tour',
    image: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80',
    highlights: ['Giraffe Centre', 'David Sheldrick Elephant Orphanage', 'Nairobi National Park'],
    itinerary: [
      { day: 1, title: 'Wildlife Morning', description: 'Visit the elephant orphanage and giraffe centre.' },
      { day: 2, title: 'National Park Drive', description: 'Afternoon game drive in the only park within a city.' },
    ],
    included: ['Entry fees', 'Transport', 'Guide'],
  },
];

export const EXPERIENCES = [
  {
    id: 'photo-tour',
    name: 'Photography Tour',
    description: 'Guided by professional wildlife photographers.',
    price: 150,
    options: ['Half-Day', 'Full-Day', 'Premium'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cultural-visit',
    name: 'Maasai Cultural Visit',
    description: 'Authentic interaction with the Maasai community.',
    price: 50,
    options: ['Standard', 'Extended'],
    image: 'https://images.unsplash.com/photo-1523805081730-6144492740ee?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'bush-dinner',
    name: 'Private Bush Dinner',
    description: 'Dining under the stars in the heart of the wild.',
    price: 120,
    options: ['Romantic', 'Family', 'Group'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
  },
];

export const ACCOMMODATIONS = [
  { id: 'budget', name: 'Adventure Camps', pricePerNight: 0, description: 'Comfortable tents with basic amenities.' },
  { id: 'mid-range', name: 'Eco Lodges', pricePerNight: 150, description: 'Sustainable luxury with great views.' },
  { id: 'luxury', name: 'Premium Safari Suites', pricePerNight: 400, description: 'Ultimate luxury with private decks and pools.' },
];

export const TRANSPORTS = [
  { id: 'shared', name: 'Shared Safari Van', price: 0, description: 'Cost-effective group travel.' },
  { id: 'private', name: 'Private 4x4 Land Cruiser', price: 200, description: 'The classic safari experience.' },
  { id: 'luxury', name: 'Luxury Executive SUV', price: 500, description: 'Maximum comfort and privacy.' },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Sarah Johnson',
    location: 'United Kingdom',
    text: 'Safari by Waweru organized the most incredible trip to Maasai Mara. Our guide was knowledgeable and the organization was flawless.',
    rating: 5,
  },
  {
    id: 2,
    name: 'David Chen',
    location: 'Singapore',
    text: 'Diani Beach was a dream. The team took care of everything, from transfers to excursions. Highly recommend!',
    rating: 5,
  },
];

export const FAQS = [
  {
    question: 'Do I need a visa for Kenya?',
    answer: 'Most international visitors require an e-visa or ETA. We recommend checking the official government portal at least 2 weeks before travel.',
  },
  {
    question: 'Is it safe to travel?',
    answer: 'Yes, Kenya is a major tourist destination. We prioritize your safety by using experienced guides and vetted accommodations.',
  },
  {
    question: 'What should I pack for a safari?',
    answer: 'Lightweight, neutral-colored clothing, a warm jacket for early mornings, sun protection, and a good pair of binoculars.',
  },
];
